object_detection:
  config_path: "E:\\projects\\smart_eye_obstacle_avoidance\\SMART_EYE_LAPTOP\\data\\models\\yolov3.cfg"
  weights_path: "E:\\projects\\smart_eye_obstacle_avoidance\\SMART_EYE_LAPTOP\\data\\models\\yolov3.weights"
  classes_path: "E:\\projects\\smart_eye_obstacle_avoidance\\SMART_EYE_LAPTOP\\data\\models\\coco.names"

face_recognition:
  known_faces_dir: data/known_faces
  db_path: data/face_db.db
  
currency_recognition:
  model_path: "E:\\projects\\smart_eye_obstacle_avoidance\\SMART_EYE_LAPTOP\\core\\currency_recognition\\model\\currency_model.h5"
  labels: ["10", "20", "50", "100", "200", "500", "2000"]

navigation:
  google_maps_api_key: "AIzaSyDqEy760yZw3ZpfGxy2VeDpIu47XKBg_9A"
  gps_update_interval: 5

obstacle_avoidance:
  serial_port: "COM11"
  alert_distance_cm: 30
